version: '3.7'
services:
  makelicense:
    image: ruby:3.3.0
    command:
      - /bin/bash
      - -c
      - |
        cd /root/license
        gem install gitlab-license
        rm -f Gitlab.gitlab-license license_key license_key.pub
        ruby license.rb 'My Name' 'My Organization' mymail@example.com"

    volumes:
      - './:/root/license:Z'
