version: '3.7'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ee:16.7.0-ee.0
    restart: always
    hostname: 'my-gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://my-gitlab.domain.my'
        gitlab_rails['initial_license_file'] = "/tmp/Gitlab.gitlab-license"

    ports:
      - '443:443'
    volumes:
      - '/gitlab/config:/etc/gitlab'
      - '/gitlab/logs:/var/log/gitlab'
      - '/gitlab/data:/var/opt/gitlab'
      - './Gitlab.gitlab-license:/tmp/Gitlab.gitlab-license'
      - './license_key.pub:/opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub'
